import frenchtoast from '../assets/images/frenchtoast.jpeg';
import babaganoush from '../assets/images/babaganoush.jpeg';
import breadcake from '../assets/images/breadcake.jpeg';
import brocoliconpasta from '../assets/images/brocoliconpasta.jpeg';
import ensaladacesar from '../assets/images/ensaladacesar.jpeg';
import nachos from '../assets/images/nachos.jpeg';
import heladochococambur from '../assets/images/heladochococambur.jpeg';
import risotto from '../assets/images/arrozcoliflor.jpeg';
import croquetas from '../assets/images/croquetasatun.jpeg';
import ensaladafrasasuvas from '../assets/images/ensaladafresas.jpeg';
import galletasmantequilla from '../assets/images/galletasmantequilla.jpeg';
import rollspandejamon from '../assets/images/rollsdepandejamon.jpeg';
import heladoronturron from '../assets/images/heladoronturron.jpeg';
import galletasjengibre from '../assets/images/galletasjengibre.jpeg';
import ponchedecrema from '../assets/images/ponchedecrema.jpeg';
import donasespeciadas from '../assets/images/donasespeciadas.jpeg';
import heladoronpasas from '../assets/images/heladoronconpasas.jpeg';
import milanesas from '../assets/images/milanesas.jpeg';
import tortadelimon from '../assets/images/tortadelimon.jpeg';
import coliflor from '../assets/images/coliflorgratinado.jpeg'
import tresleches from '../assets/images/tresleches.jpeg';
import ricecrispies from '../assets/images/ricecrispies.jpeg';
import platanitos from '../assets/images/platanitos.jpeg';

const RECIPES = [
    {"title":"French Toast", "image":frenchtoast, "url":"https://www.instagram.com/p/Cjqzm3VO3oA/", "text":"Como me la pidieron demasiado hoy les quiero compartir la receta de FrenchToast que me tiene 🫶🏽", "ingredients":["3 claras de huevo", "2 rebanadas de pan integral", "Chorrito de leche (la que uses), Canela, Edulcorante", "Toppings de tu preferencia: Frutas, mantequilla de frutos secos, sirope sugar free, chocolate derretido, queso de cabra, queso feta, etc."], "preparation":["En un envase rectangular mezcla bien las claras de huevo, el chorrito de leche, la canela y el edulcorante.", "Pon a remojar tus rebanadas de pan en la mezcla anterior, dales vuelta a los minutos, buscando que el pan absorba toda la mezcla.", "Pon a calentar a fuego medio un sartén o plancha antiadherente.", "Una vez el pan haya absorbido toda la mezcla colócalo en el sartén.", "Cocina por ambos lados hasta dorar.", "Sirve con los toppings de tu preferencia y disfruta"]},
    {"title":"Baba Ganoush", "image":babaganoush, "url":"https://www.instagram.com/p/Cgh3Oq5u3pE/", "text":"Hoy te regalo esta receta que no puede faltar en mi nevera para que no te falte en la tuya tampoco!😏", "ingredients":["5 berenjenas tamaño mediano", "2 1/2 cucharaditas sal", "1 1/2 cucharadita de ajo molido natural", "1 cucharadita de comino", "Zumo de limón al gusto (jugo de limón y medio aprox.)"], "preparation": ["Debes asar tus berenjenas directamente sobre la llama de la estufa, literalmente debes dejarlas quemadas (la piel de las berenjenas debe quedar 100% negra, de esto dependerá el sabor ahumado del puré).", "Coloca las berenjenas dentro de una bolsa de plástico para que se suden y sea fácil quitarles la piel.", "Luego de 15-20 minutos, abre la bolsa y quítales la piel.", "Coloca la pulpa de berenjena en un procesador de alimentos o en la licuadora.", "Añade el resto de los ingredientes y procesa hasta obtener una mezcla homogénea.", "Guarda el puré en un envase hermético y disfruta de tu crema de berenjena cada vez que lo desees."]},
    {"title":"Torta de Pan Integral","image":breadcake,"url":"https://www.instagram.com/p/CXAAKgbNBCj/", "text":"Hoy te regalo esta receta que no puede faltar en mi nevera para que no te falte en la tuya tampoco!😏", "ingredients":["500 ml de leche (la que uses, yo utilicé de almendras)","2 huevos","8 ó 9 rebanadas de pan integral","3/4 de taza de edulcorante cristalino (monkfruit, eritritol, xilitol, alulosa, azúcar de coco)(yo utilicé monkfruit golden)","1 cdta. de vainilla","1 1/2 cdta. de canela molida.","Pizca de sal","Opcional: chorrito de Ron (o esencia de ron), pasas al gusto."], "preparation":["Con tus manos desmenuza bien las rebanadas de pan y colócalas en un bowl.","Entibia la leche en el microondas.", "Incorpora la leche tibia a las rebanadas de pan, agrega la vainilla y la canela, con ayuda de un tenedor asegúrate de que todo el pan se sumerja en la leche.", "Deja que el pan se ablande lo suficiente, para ello transcurrirán unos 15-20 min, de vez en cuando puedes repetir la operación con el tenedor.", "Incorpora los huevos a la mezcla con un batidor de mano y remueve bien.", "Agrega el edulcorante y continúa removiendo."]},
    {"title":"Croquetas de Atún", "image": croquetas,"url":"https://www.instagram.com/p/CTXVl-Ogq5e/", "text":"Apareciendo por acá después de meses sin publicar recetas en mi feed y vengo con par de recetas INCREÍBLES 🤩", "ingredients":["2 latas pequeñas de atún en agua","2 huevos","3 rebanadas de Wasa Bread (o de pan integral)","1 puñado de perejil (opcional)","½ taza de cebolla picada en cuadritos","2 cucharadas de pimentón rojo picado en cuadritos.","Sal y pimienta al gusto"],"preparation":["Escurre el atún y desmenúzalo bien.","Pon a tostar tus rebanadas de pan, déjalas enfriar bien y tritúralas. (Si lo haces con WASA solo debes triturarlas, no las vayas a tostar 🤦🏽‍♀️).","Mezcla el atún y el pan triturado con el resto de los ingredientes hasta integrar bien.","Coloca la masa resultante del paso 3 en la nevera unos 20 min para que agarre un poco más consistencia antes de moldearla.","Moldea la masa con tus manos formando las croquetas.","Colócalas sobre la bandeja de tu AirFryer (puedes rociarlas con aceite de oliva en spray) y cocínalas a 350F hasta dorar (revísalas a partir del minuto 15 cada 5 min, dependerá de tu AirFryer) o puedes cocinarlas en el horno, colocándolas sobre una bandeja antiadherente a 350F hasta dorar.", "Sirve y disfruta con tu salsa tártara fit."]},
    {"title":"Ensalada César", "image":ensaladacesar, "url":"https://www.instagram.com/p/CVByC9otC0V/", "text":"¿Toda tu vida has estado buscando la receta perfecta de la increíblemente deliciosa ENSALADA CÉSAR?", "ingredients":["Pan Integral", "3/4 taza de yogurt griego","6 filetes de anchoas", "2 dientes de ajo", "1 1/2 cda. de zumo de limón", "1 1/2 cdta. de mostaza dijon (o mostaza regular)", "20 g de queso parmesano","1/4 cdta. de sal", "Pechuga de pollo entera deshuesada", "Lechuga Romana", "Tocineta (Opcional)"], "preparation":["Corta pan integral en cuadritos con un cuchillo de sierra, coloca los cuadritos de pan integral en el airfryer y rocíalos con aceite de oliva en spray, cocínalos 10 min a 350F (revísalos a los 7 min a ver como van).", "Coloca todos los ingredientes para el aderezo en un batidor de mano o licuadora y procesa hasta obtener una mezcla homogénea.", "Marina la pechuga de pollo durante 1 hora con limón, ajo, sal y pimienta. Luego de transcurrido el tiempo SELLA tus pechugas en un sartén a fuego alto, una vez esté dorada por todas sus caras llévalas al airfryer a 350F durante 12-15 min.", "En un bowl lo suficientemente grande coloca tu lechuga, parte de los croutones y el aderezo, remueve con mucho amor hasta que todas las hojas de lechuga estén cubiertas de este aderezo de los dioses. Sirve la lechuga, colócale extra de croutones por encima, tocineta troceada, un toque de queso parmesano, a un lado la pechuga de pollo y a comer"]},
    {"title":"Nachos Saludables", "image":nachos, "url":"https://www.instagram.com/p/CPbhxPthBpG/", "text":" ¿ERES AMANTE DE LOS NACHOS? 😏😍 ¡Entonces esta comida super saludable es para ti! ¡LA AMARÁS!🤤", "ingredients":["Carne Molida", "Chips de Batata", "Pico de gallo: Tomate, cebolla morada y cilantro. Mi recomendación es que adereces el pico de gallo con Limón, tabasco verde y sal.", "Crema agria: Yogurt griego, limón y sal. Así al ojo por ciento, ve probando hasta que quede a tu gusto.", "Guacamole (no tenía aguacate, esta receta fue muy improvisada, pero puedes colocarle): Yo lo hago llevando a un procesador o licuadora aguacate, limón, ajo, un chorrito de vinagre y sal.", "Para decorar cilantro, cilantro y más cilantro."], "preparation":["Quita la piel de las batatas.","Corta láminas muy delgadas, puedes hacerlo con un cuchillo, con una mandolina o con una rebanadora.","Coloca sobre una bandeja de horno con un silpat o papel encerado tus chips (también puedes hacerlo directamente sobre la bandeja pero asegúrate de colocarle aceite) coloca tus láminas sin sobreponerlas unas sobre otras.","Rocía aceite de oliva en spray sobre ellas y luego un poco de sal (si no tienes aceite de oliva en spray, antes de colocarlas en la bandeja agrégales un chorrito de aceite de oliva a tus láminas y asegúrate de espárcirlo bien con tus manos).","Lleva al horno a 180C durante 15-20 min, (va a depender de tu horno, te recomiendo estés pendiente) cuando las veas doraditas ya estarán.", "Ensambla las preparaciones restantes y disfruta 💃🏽💃🏽"]},
    {"title":"Helado de Chococambur", "image":heladochococambur, "url":"https://www.instagram.com/p/CN8QnvABFoK/", "text":"Y como ustedes lo pidieron les tengo la “receta” de mi merienda favorita de todos los días 😍","ingredients":["2 cambures grandes congelados","1 scoop de proteína de chocolate o vainilla(opcional)","1 cucharada de cacao en polvo"],"preparation":["En una licuadora de alta potencia licúa todos los ingredientes, puedes agregar un chorrito de la leche de tu preferencia o agua si se te dificulta procesarlo.","Licúa hasta tener una mezcla homogénea.", "Sirve y disfruta."]},
    {"title":"Risotto Low Carb","image":risotto, "url":"https://www.instagram.com/p/CNGSqIlhw_V/","text":"¿Risotto Low Carb? 🤔 ¿Sin arroz? 🧐¿Megadelicioso? 🤯¡Te lo tengo! Y no te imaginas lo divino que te va a quedar", "Ingredients":["300 g de flores de coliflor crudo","250 g de champiñones fileteados", "1/2 cebolla grande picada finamente", "1 cucharada de aceite de oliva", "30 g (o más de queso parmesano)", "Perejil o cebollín (picado finamente) para decorar", "Sal y pimienta al gusto"], "preparation":["Lava bien tus flores de coliflor, sécalas y pásalas por un picatodo hasta que tengas los granos del tamaño de granos de arroz.","Coloca en un sartén el aceite de oliva a fuego medio/alto, una vez esté bien caliente incorpora la cebolla y cocina a fuego medio hasta cristalizar.","Una vez la cebolla esté cristalina, incorpora los champiñones, cocina a fuego medio hasta que comiencen a botar su jugo.","Un minuto después agrega el coliflor previamente procesado, agrega sal, pimienta y tapa el sartén.","Cocina la preparación tapada durante 5 minutos removiendo ocasionalmente.","Destapa tu preparación y cocina durante 5 minutos mas removiendo ocasionalmente, sabrás que está listo por que al probarlo los “granos” de coliflor estarán suaves como un grano de arroz cocido.","En este momento, apaga el fuego e inmediatamente incorpora el queso parmesano removiendo hasta integrar en su totalidad.","Acompáñalo de tu proteina favorita y disfruta, si gustas puedes decorar con un poco de perejil o cebollín por encima."]},
    {"title":"Ensalada con Fresas, Uvas verdes y Queso de cabra",  "image":ensaladafrasasuvas, "url":"https://www.instagram.com/p/CdJutRuumKn/", "text":"NO TE GUSTAN LAS ENSALADAS? 😱 Te prometo que a esta no te podrás resistir! 💘","ingredients":["Hojas de lechuga romana fresca (O mix de lechugas)","Fresas", "Uvas verdes (opcional)", "Queso de cabra cremoso", "1 cucharada de aceite de oliva", "1 cucharada de vinagre balsámico de Modena DOP", "una pizca de sal."], "preparation":"Esambla todo como en la imagen y a disfrutar"},
    {"title":"Galletas de Mantequilla", "image":galletasmantequilla, "url":"https://www.instagram.com/p/CYFiQyMuwpf/", "text":"Hoy les voy a compartir una receta que se robó mi corazón. Esas que se regalan en Navidad, que vienen dentro de una lata de aluminio", "ingredients":["150 gramos de harina de avena.","100 gramos de harina de almendras.", "1 cucharada de linaza molida.", "1 huevo.", "120 gramos de ghee", "120 gramos de eritritol (puedes sustituir por xilitol, monkfruit o azúcar de coco)", "Pizca de sal.", "1 cucharadita de polvo de hornear"], "preparation":["Integra bien los ingredientes secos.","Añade los ingredientes húmedos e íntegra hasta tener una mezcla homogénea, por ultimo añade el polvo de hornear y la sal, incorpora bien.", "Coloca la mezcla en la manga o en la pistola de galletas y realiza la figura deseada sobre una bandeja para horno (sin papel encerado, ellas no se van a pegar.","Si gustas colócales chispas por encima.", "Lleva al horno a 180 grados durante 10-12 minutos.", "Déjalas enfriar bien; es normal que al salir del horno estén un poco suaves.", "Disfrútalas 😋."]},
    {"title":"Rolls de Pan de Jamon", "image":rollspandejamon, "url":"https://www.instagram.com/p/CXxBlcJOPCK/", "text":"Si el año pasado amaste mi receta de pan de jamón de yuca🤤, este año no te puedes perder estos rolls.", "ingredients":["200 g de Harina de trigo integral", "200 g de Yogurt griego", "1 cdta. de polvo de hornear", "Una pizca de sal", "Jamón de pavo", "Aceitunas", "Uvas pasas"], "preparation":["Precalienta el horno a 180C.","En un bowl grande mezcla los ingredientes secos hasta integrar bien.", "Incorpora el yogurt y mezcla utilizando una espátula de silicona o una cucharilla, hasta que se forme una bola rústica.", "Transfiere la pasa a una superficie de trabajo ligeramente enharinada y amasa con las manos durante 2-3 minutos hasta formar una masa.", "Con un rodillo extiende tu masa sobre la superficie (puedes utilizar papel encerado o plástico para ayudarte a extender la masa sin que se pegue de la superficie o del rodillo), corta los bordes para que quede un rectángulo perfecto.","Llegó el momento de rellenar y enrollar tu pan; para que aprendas a hacerlo te preparé un video que publicaré el día de mañana.", "Coloca tus rolls sobre una bandeja con papel encerado, barnizalos con huevo y hornea durante 30-35 minutos a 180C.", "Déjalos enfriar, sirve y disfrútalos."]},
    {"title":"Helado de Ron con Turron", "image":heladoronturron, "url":"https://www.instagram.com/p/CXumv5buXbV/", "text":"¿Eres amante del helado? Esta receta es para ti 🤩", "ingredients":["2 tazas (500ml) de leche de coco (debes usar la de lata, full fat, si quieres una textura como la del video)", "¼ de taza de aceite de coco", "1/3 de taza de sirop de maple sugar free + 6 sobresitos de splenda (o sustituye todo por tu endulzante favorito al gusto)", "¼ de taza de ron oscuro", "1 cucharadita de extracto de ron con pasas (o vainilla)", "1 pizca de sal", "1 barra de turrón de chocolate sin azúcar (de @glutenfree.store)"], "preparation":["Añade la leche de coco, el aceite, el sirop de maple, la splenda, el ron, el extracto de ron con pasas y la sal a una licuadora, licúa a velocidad máxima durante 8-10 minutos.","Lleva al congelador en una hielera o en moldes de silicona durante 7 horas (toda la noche)", "30 minutos antes de sacar tus cubos del congelador, coloca a hervir una ollita con agua y remoja tus pasas en agua hirviendo por 1 minuto, escúrrelas bien.", "Transcurrido el tiempo coloca todos los cubos con tu preparación en una licuadora a máxima velocidad, ayúdate con un tamper de ser necesario para que se integre bien la mezcla. Los cubos quedan bastante cremosos asi que no será tan difícil que se vuelvan una pasta.", "Licúa hasta que tenga la consistencia de una crema, vierte la preparación en un molde apto para congelador.", "Trocea el turrón y colócalo de topping sobre tú helado.", "Lleva al congelador 45 minutos y disfruta."]},
    {"title":"Galletas de Jengibre", "image":galletasjengibre, "url":"https://www.instagram.com/p/CXjsXfnOKEJ/", "text":"¡Y CON USTEDES LLEGÓ EL TRENCITO DE LA FELICIDAD!🎄🚂", "ingredients":["1 taza de harina de avena","2 cucharadas de mantequilla de merey (puedes sustituir por cualquier mantequilla de frutos secos)", "2 cucharadas de aceite de coco (líquido)", "2 cucharadas de sirup sugar free (o miel)", "1 huevo", "1 cda. De esencia de vainilla", "2 cdtas. de gengibre en polvo", "1 cdta. de canela", "Stevia líquida al gusto"], "preparation":["Incorpora en un bowl todos los ingredientes secos.","En otro bowl incorpora los húmedos.", "Integra bien los húmedos en los secos hasta obtener una masa homogénea.", "Extiende la masa con ayuda de un rodillo y córtala con un cortador de galletas.", "Hornea en una bandeja con un silpat o papel encerado.", "Hornea a 165C (horno precalentado) durante 15 min.", "Deja enfriar bien tus galletas antes de retirarlas de la bandeja.", "Cuando se encuentren completamente frías decora con el ICING."]},
    {"title":"Ponche de Crema", "image":ponchedecrema, "url":"https://www.instagram.com/p/CXZSL3NuScT/", "text":"Y con ustedeeess: la receta del PONCHE CREMA más divino y saludable que se puedan tomar!💁🏽‍♀️", "ingredients":["1 L de leche (yo utilicé de almendras SILK)", "1/3 taza de eritritol (xilitol, monkfruit o azúcar de coco)", "2 ramas de canela", "5 clavos de especias", "4 o 5 yemas", "30 g de maicena", "4 scoops de proteina en polvo de vainilla (yo utilicé ISO100)", "1/2 taza de ron (aunque si te soy muy honesta, queda muuucho mejor con 2/3 tazas de ron 🤪)", "1/4 cdta. De canela en polvo", "1/8 cdta. De clavos de especias en polvo", "1/8 cdta. Nuez moscada en polvo"], "preparation":[]},
    {"title":"Donas Especiadas Navideñas", "image":donasespeciadas, "url":"https://www.instagram.com/p/CXSFPsMuqQS/", "text":"¡Si te gusta el sabor a navidad esta receta es para ti! 💁🏽‍♀️", "ingredients":["2 huevos","1 taza de harina de almendras", "1 cucharada de mantequilla de merey Protein vainilla @edellafit (sustituible por cualquier mantequilla de frutos secos)", "2 cucharadas de sirope sugar free (o miel)", "1/4 taza de endulzante (yo utilicé alulosa)", "1 cdta. de jengibre en polvo", "1 cdta. de canela en polvo", "1 cdta. de vainilla", "1 cdta. De polvo de hornear"], "preparation":[]},
    {"title":"Brocoli con Pasta", "image":brocoliconpasta, "url":"https://www.instagram.com/p/CMgDQ8chGPJ/", "text":"¿Estas antojad@ de comer pasta y no la comes por que crees que no es saludable?", "ingredients":["4 tazas de arboles de brócoli", "1/2 taza de pasta corta", "2 cucharadas de queso parmesano", "1 cucharada de aceite de oliva", "2 cucharaditas de ajo","Sal","Peperoncino al gusto"], "preparation":["Coloca agua en una olla y llévala a hervor.","Una vez hierva incorporaa un poco de sal y tus brócolis.","Hierve tus brócolis hasta que estén al dente, con ayuda de un escurridor saca los brócolis del agua hirviendo y traspasalos aa un bowl con agua con hielo (para que no se marchiten ni continúen cociéndose).","Cocina tu pasta en el agua de los brócolis, déjala al dente.","Mientras se cocina la pasta, coloca en un sarten a fuego medio el aceite de oliva y el ajo.","Cuando escurras tu pasta reserva una taza del agua de cocción.","Incorpora en el sartén que tiene el aceite y el ajo, la pasta, los brócolis, el queso parmesano y ¼ de taza del agua de cocción, continúa cocinando a fuego medio/bajo hasta que el aceite, el agua de cocción y el queso formen especie de una crema.", "Esparce peperoncino al gusto por encima y Disfruta de este delicioso contorno!"]},
    {"title":"Helado de Ron con Pasas", "image":heladoronpasas, "url":"https://www.instagram.com/p/CMQaARwh-rA/", "text":"Les confieso que esta receta la hice pensando en mi Mamá, desde que era muy pequeña recuerdo verla *delirar* 🥰 por su helado favorito “RON CON PASAS”", "ingredients":["2 tazas (500ml) de leche de coco (debes usar la de lata, full fat, si quieres una textura como la del video)","¼ de taza de aceite de coco","1/3 de taza de sirop de maple sugar free + 6 sobresitos de splenda (o sustituye todo por tu endulzante favorito al gusto)","¼ de taza de ron oscuro","1 cucharadita de extracto de ron con pasas (o vainilla)","1 taza de pasas","1 pizca de sal"], "preparation":[]},
    {"title":"Milanesa a la Parmesana", "image":milanesas, "url":"https://www.instagram.com/p/CL5TfGqB40s/", "text":"TE TENGO LA MEJOOOOR IDEA PARA EL ALMUERZO DE MAÑANA 🤩!", "ingredients":["80 gr casabe molido","2 filetes de pechuga de pollo grandes","1 huevo","Ajo natural molido","Mostaza","Sal y pimienta","Aceite de oliva","1/2 taza de salsa filetto","20g Queso parmesano"], "preparation":["Con ayuda de un martillo pisa las pechugas de pollo hasta extenderlas bien, condiméntalas con mostaza, ajo, sal y pimienta.", "En un plato hondo bate el huevo con ayuda del tenedor, colócale sal.", "En otro plato hondo coloca el casabe molido.", "Pasa tus milanesas condimentadas por huevo y posteriormente empanizalas con el casabe molido.", "En un sartén coloca aceite de oliva en spray a fuego medio/alto; dora tus milanesas (no debes cocinarlas completamente, solo dorarlas)", "Lleva tus milanesas al horno a 180C durante 15-20 min (puedes hacerlo en el AirFryer también).", "Sácalas del horno, esparce por encima de cada milanesa un poco de salsa filetto y queso parmesano.", "Llévalas al horno nuevamente hasta que el queso se dore."]},
    {"title":"Torta de Limón", "image":tortadelimon, "url":"https://www.instagram.com/p/CLz41oTBiLE/", "text":"Quiero describirles mi sensación con esta receta: El día que fotografíamos esta torta me comí 4 pedazos durante la sesión, no podía parar.", "ingredients":["1 1/2 taza de harina de almendras","1/2 taza de avena en hojuelas instantáneas","1 taza de monkfruit (o el endulzante cristalino de tu preferencia)","2 huevos (separadas las yemas de las claras)","1/4 taza de aceite de coco","1 taza de yogurt griego","Zumo de 2 limones","Ralladura de 2 limones","2 cdas. de polvo de hornear"], "preparation":[]},
    {"title":"Coliflor Gratinado", "image":coliflor, "url":"https://www.instagram.com/p/CLsQ2xQhZJC/", "text":"Healthy Fam, me escriben muchísimo pidiéndome opciones para la cena así que siempre estoy pensando en qué receta compartirles para poder llevar sus cenas de algo tradicional a algo FENOMENAL🤩", "ingredients":["Coliflor grande (cocido al vapor)","50 g de merey (o más)", "1/2 cebolla picada en trozos (o más)", "Queso parmesano", "Queso mozarella", "Aceite de oliva", "Perejil picado finamente", "Sal y pimienta"], "preparation":["Coloca a hervir una olla con agua.","Apaga el fuego y vierte los mereyes en el agua hirviendo, déjalos remojar durante una hora.", "Mientras tanto sofríe la cebolla en un sartén con un poquito de aceite de oliva hasta cristalizar, reserva.", "Una vez haya transcurrido la hora, coloca en un procesador de alimentos o licuadora los mereyes escurridos, la cebolla, sal y pimienta al gusto; procesa hasta obtener una consistencia cremosa (si es necesario agrega un chorrito de agua para que no quede tan densa y sea más fácil de procesar).", "Coloca en un refractario para horno el coliflor previamente cocido al vapor, por encima esparce la crema de merey y sobre ella coloca queso mozarella y queso parmesano.", "Lleva al horno en modalidad “broil” hasta dorar (unos 5 minutos).", "Coloca perejil por encima y disfruta de esta delicia."]},
    {"title":"Tres Leches", "image":tresleches, "url":"https://www.instagram.com/p/CLc-_tqBZn-/", "text":"Ustedes lo pidieron y aquí la tienen:¡LA TRES LECHES MAS DIVINA Y SALUDABLE QUE HAN PROBADO!🥳 No tienen idea de lo deliciosisima🤤 que quedó esta receta", "ingredients":["2 huevos","40 g de harina de almendras","20 g de harina de avena","6 cucharadas de monkfruit","4 cucharadas de leche de almendras","1 cdta. de aceite de coco","½ cdta de polvo de hornear","1 taza de leche de almendras","½ scoop de proteína de vainilla (opcional, puedes obviarla y agregar esencia de vianilla + edulcorante)", "3 cucharadas de leche descremada en polvo", "2 claras de huevo", "1 cucharada de Monkfruit pulverizado"], "preparation":["Separa la yema de las claras.","En un bowl y con ayuda de una batidora eléctrica, mezcla las yemas con el resto de los ingredientes del biscocho, bate hasta obtener una mezcla homogénea.", "En un bowl aparte monta las claras de huevo.","Incorpora las claras al resto de la preparación con movimientos envolventes.","Hornea a 180C durante 40 min.","Deja enfriar el biscocho 10 min, desmolda y colocalo en un envase mas grande.","Realiza agujeros en el biscocho con ayuda de un tenedor.","Mezcla las “3 leches”, una vez tengas una mezcla homogénea, baña tu biscocho con la mezcla.","Llevalo a la nevera durante 2 horas o más.","Prepara tu merengue batiendo las claras a alta velocidad con una batidora eléctrica, una vez comiencen a montar incorpora el edulcorante.","Saca tu biscocho de la nevera, decora con merengue y esparce canela en polvo por encima."]},
    {"title":"", "image":ricecrispies, "url":"", "text":"", "ingredients":[], "preparation":[]},
    {"title":"", "image":platanitos, "url":"", "text":"", "ingredients":[], "preparation":[]},
    {"title":"", "image":"", "url":"", "text":"", "ingredients":[], "preparation":[]},
    {"title":"", "image":"", "url":"", "text":"", "ingredients":[], "preparation":[]},
]

export default RECIPES;
console.log(`${RECIPES.length} recipes are loaded!`);